# ============================================================
#  Proyecto3 - E-Commerce UTS
#  application.properties
# ============================================================

# Servidor
server.port=8080

# Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Mensajes
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Logging
logging.level.com.proyecto3=DEBUG
logging.level.org.springframework.security=DEBUG
